Docker: More efficient builds and less layers in final image.
More layers in first stage, less in final one by compressing ENVs into
on ENV statement.

Had to update git and openssh versions, because of
ERROR: unsatisfiable constraints:
  git-2.18.1-r0:
    breaks: world[git=2.18.0-r0]
    satisfies: alpine-sdk-1.0-r0[git]
  openssh-7.7_p1-r4:
    breaks: world[openssh=7.7_p1-r3]